environment: PUI_ENV
database:
  name: POSTGRES_DB_NAME
  host: POSTGRES_SERVER_NAME
  username: POSTGRES_USERNAME
  port: POSTGRES_SERVER_PORT
  ssl: POSTGRES_SSL
secrets:
  rpx:
    postgresql-admin-pw: POSTGRES_PASSWORD
    appinsights-instrumentationkey-tc: APPINSIGHTS_INSTRUMENTATIONKEY
proxy:
  host: PROXY_HOST
  port: PROXY_PORT
client:
  whitelist: CLIENT_WHITELIST
services:
  s2s: S2S_TOKEN_URL
  idam:
    api-url: IDAM_SERVICE_URL